In [1]:
mylist = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(mylist)

In [4]:
arr

array([1, 2, 3])

In [5]:
mymat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
mymat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(mymat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
np.linspace(0,5,11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.61710378, 0.50349993, 0.19008953, 0.34577507, 0.86545914])

In [18]:
np.random.rand(5,5)

array([[0.82499619, 0.99925652, 0.44033228, 0.92027774, 0.65559892],
       [0.42666319, 0.15064268, 0.78607037, 0.82533652, 0.94763088],
       [0.19325853, 0.44804615, 0.83385757, 0.83161397, 0.35491185],
       [0.44813053, 0.87954247, 0.83430925, 0.13469769, 0.82584276],
       [0.39482477, 0.63273018, 0.12021206, 0.25912317, 0.88807439]])

In [20]:
np.random.randn(4,4)

array([[ 0.09982419, -2.24659977,  0.42509984,  0.55658819],
       [ 0.37540622,  0.75176031, -0.23606806,  0.77887598],
       [ 0.52275407, -1.38782283,  0.48722315,  1.00887962],
       [ 1.15294541,  1.00623507, -1.52419514,  0.81898797]])

In [22]:
np.random.randint(1,100,10)

array([53, 45,  5, 24, 40, 78, 30,  3, 48, 96])

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0,50,10)

In [27]:
ranarr

array([23, 26,  8, 12, 12, 49, 15, 40, 13, 23])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr.max()

49

In [30]:
ranarr.min()

8

In [31]:
ranarr.argmax()

5

In [32]:
ranarr.argmin()

2

In [40]:
arr.shape

(25,)

In [41]:
arr = arr.reshape(5,5)

In [42]:
arr.shape

(5, 5)

In [43]:
arr.dtype

dtype('int32')

In [50]:
from numpy.random import randint, randn

In [51]:
randint(2,10)

8

In [52]:
randn(10)

array([-0.0482418 ,  0.27069175,  2.03329426,  0.24198981, -0.16066646,
       -2.39634294, -1.49913008, -0.46321274,  1.44869489, -1.68157583])