In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [7]:
arr[1::-1]

array([1, 0])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[4::]

array([ 4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[4::2]

array([ 4,  6,  8, 10])

In [11]:
arr[4::-2]

array([4, 2, 0])

In [12]:
arr[4::-1]

array([4, 3, 2, 1, 0])

In [13]:
arr[:-3:-1]

array([10,  9])

In [14]:
arr[:-3:1]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
arr[7::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
arr[7:-2:-1]

array([], dtype=int32)

In [17]:
arr[7:-1:-1]

array([], dtype=int32)

In [18]:
arr[5:-1]

array([5, 6, 7, 8, 9])

In [21]:
arr[5:-1:2]

array([5, 7, 9])

In [22]:
arr = np.arange(0,11)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
slice_of_arr = arr[0:6]

In [25]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [26]:
arr_copy = arr.copy()

In [27]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr_copy[:5] = 99

In [29]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [33]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr_2d[0][0]

5

In [35]:
arr_2d[0]

array([ 5, 10, 15])

In [36]:
arr_2d[1][1]

25

In [37]:
arr_2d[1,1]

25

In [39]:
arr_2d[2,0:2]

array([35, 40])

In [40]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [41]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [44]:
arr_2d[0:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [45]:
arr_2d[1:,::-1]

array([[30, 25, 20],
       [45, 40, 35]])

In [46]:
arr_2d[::-1,::-1]

array([[45, 40, 35],
       [30, 25, 20],
       [15, 10,  5]])

In [47]:
arr_2d[:,::-1]

array([[15, 10,  5],
       [30, 25, 20],
       [45, 40, 35]])

In [49]:
arr = np.arange(1,11)

In [50]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
bool_arr = arr > 5

In [53]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [54]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [55]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [56]:
arr[arr<3]

array([1, 2])

In [57]:
arr_2d = np.arange(50).reshape(5,10)

In [58]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [59]:
arr_2d[1:3,::-2]

array([[19, 17, 15, 13, 11],
       [29, 27, 25, 23, 21]])

In [63]:
arr_2d[:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [65]:
arr_2d[-1,:6:-1]

array([49, 48, 47])

In [66]:
arr_2d[-2,:6:2]

array([30, 32, 34])